spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: spring.datasource.local.jdbc-url=jdbc:mysql://192.168.1.100:3366/hy_db?characterEncoding=utf8&allowMultiQueries=true
  jpa:
    show-sql: true